# Generated by Django 3.2.9 on 2023-12-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts_of_computer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categortFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.CreateModel(
            name='RamFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_Type', models.CharField(max_length=255, null=True)),
                ('ram_Capacity', models.CharField(max_length=255, null=True)),
                ('ram_Frequency', models.CharField(max_length=255, null=True)),
                ('channel_Type', models.CharField(max_length=255, null=True)),
                ('ram_Compatibility', models.CharField(max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RamFeature', to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_Model', models.CharField(max_length=255, null=True)),
                ('processor_Manufacturer', models.CharField(max_length=255, null=True)),
                ('processor_Socket_Type', models.CharField(max_length=255, null=True)),
                ('processor_Series', models.CharField(max_length=255, null=True)),
                ('core_Count', models.CharField(max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProcessorFeature', to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='MouseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_Type', models.CharField(max_length=255, null=True)),
                ('tracking_Type', models.CharField(max_length=255, null=True)),
                ('button_Count', models.CharField(max_length=255, null=True)),
                ('usage_Type', models.CharField(max_length=255, null=True)),
                ('max_DPI', models.CharField(max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MouseFeature', to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_Socket_Type', models.CharField(max_length=255, null=True)),
                ('ram_Type', models.CharField(max_length=255, null=True)),
                ('compatible_Processors', models.CharField(max_length=255, null=True)),
                ('motherboard_Size', models.CharField(max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MotherboardFeature', to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_Size', models.CharField(max_length=255, null=True)),
                ('resolution', models.CharField(max_length=255, null=True)),
                ('refresh_Rate', models.CharField(max_length=255, null=True)),
                ('panel_Type', models.CharField(max_length=255, null=True)),
                ('response_Time', models.CharField(max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MonitorFeature', to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='KeyboardFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_Type', models.CharField(max_length=255, null=True)),
                ('mechanical', models.BooleanField(null=True)),
                ('keyboard_Layout', models.CharField(max_length=255, null=True)),
                ('wrist_Support', models.BooleanField(null=True)),
                ('numpad', models.BooleanField(null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='KeyboardFeature', to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsCardFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_Manufacturer', models.CharField(max_length=255, null=True)),
                ('gpu_Model', models.CharField(max_length=255, null=True)),
                ('memory_Type', models.CharField(max_length=255, null=True)),
                ('gpu_Memory_Capacity', models.CharField(max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GraphicsCardFeature', to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CoolerFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatible_Sockets', models.CharField(max_length=255, null=True)),
                ('cooling_Type', models.CharField(max_length=255, null=True)),
                ('led', models.CharField(max_length=255, null=True)),
                ('radiator_Size', models.CharField(max_length=255, null=True)),
                ('fan_Count', models.IntegerField(null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CoolerFeature', to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerCaseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_Type', models.CharField(max_length=255, null=True)),
                ('PSU', models.CharField(max_length=255, null=True)),
                ('PSU_Location', models.CharField(max_length=255, null=True)),
                ('transparent_Case', models.CharField(max_length=255, null=True)),
                ('type_C', models.CharField(max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ComputerCaseFeature', to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooling_Type', models.CharField(max_length=255, null=True)),
                ('fan_Count', models.CharField(max_length=255, null=True)),
                ('led_Type', models.CharField(max_length=255, null=True)),
                ('power_Connector', models.CharField(max_length=255, null=True)),
                ('rpm', models.CharField(max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CaseFanFeature', to='parts_of_computer_app.product')),
            ],
        ),
    ]
