# Generated by Django 3.2.9 on 2023-12-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts_of_computer_app', '0002_auto_20231214_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categortFeature',
            new_name='CategoryFeature',
        ),
    ]
